In [1]:
!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000248B5E12630>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/ipykernel/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000248B5E126D8>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/ipykernel/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000248B5E12A90>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/ipykernel/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connect

In [9]:
! pip install graphviz


You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [17]:
### Add the dot to  path
import sys
sys.path.append('C:/ProgramData/Anaconda3/Library/bin/dot.bat')
### Add the Grpahviz bin to file path
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

In [18]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
from sklearn.datasets import load_wine
from IPython.display import SVG
from graphviz import Source
from IPython.display import display                               
from ipywidgets import interactive
# load dataset
data = load_wine()
# feature matrix
X = data.data
# target vector
y = data.target
# class labels
labels = data.feature_names

def plot_tree(crit, split, depth, min_split, min_leaf=0.2):
    estimator = DecisionTreeClassifier(random_state = 0 , criterion = crit , splitter = split , max_depth = depth  , min_samples_split=min_split, min_samples_leaf=min_leaf)
    estimator.fit(X, y)
    graph = Source(tree.export_graphviz(estimator, out_file=None, feature_names=labels, class_names=['0', '1', '2'], filled = True))   
    display(SVG(graph.pipe(format='svg')))
  
    return estimator



inter=interactive(plot_tree  , crit = ["gini", "entropy"], split = ["best", "random"] , depth=[1,2,3,4] , min_split=(0.1,1) , min_leaf=(0.1,0.5))
display(inter)




interactive(children=(Dropdown(description='crit', options=('gini', 'entropy'), value='gini'), Dropdown(description='split', options=('best', 'random'), value='best'), Dropdown(description='depth', options=(1, 2, 3, 4), value=1), FloatSlider(value=0.55, description='min_split', max=1.0, min=0.1), FloatSlider(value=0.2, description='min_leaf', max=0.5, min=0.1), Output()), _dom_classes=('widget-interact',))

In [22]:

from sklearn.model_selection import train_test_split  
# load dataset
data = load_wine()
# feature matrix
X = data.data
# target vector
y = data.target
# class labels
labels = data.feature_names


from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 
y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 13  0]
 [ 1  0 10]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96        12
          1       1.00      1.00      1.00        13
          2       1.00      0.91      0.95        11

avg / total       0.97      0.97      0.97        36



In [ ]:
### Decision Trees for Regression

In [24]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [26]:
dataset = pd.read_csv('petrol_consumption.csv')  
dataset.head(5)  

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [27]:
dataset.describe()  

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

In [29]:
X = dataset.drop('Petrol_Consumption', axis=1)  
y = dataset['Petrol_Consumption']  
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [30]:
from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor()  
regressor.fit(X_train, y_train)  

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [32]:
y_pred = regressor.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})  
df  

Actual  Predicted
29     534      547.0
4      410      414.0
26     577      554.0
30     571      554.0
32     577      631.0
37     704      644.0
34     487      648.0
40     587      649.0
7      467      414.0
10     580      464.0

In [33]:
from sklearn import metrics  
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  

###The mean absolute error for our algorithm is 54.7, which is less than 10 percent of the mean of all the values in 
###the 'Petrol_Consumption' column. This means that our algorithm did a fine prediction job.

Mean Absolute Error: 56.3
Mean Squared Error: 5354.9
Root Mean Squared Error: 73.17718223599485


In [34]:
## Random Forest 
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [41]:
# Actual class predictions
rf_predictions = model.predict(X_test)
# Probabilities for each class
rf_probs = model.predict_proba(X_test)[:, 1]
rf_predictions, rf_probs

(array([547, 540, 628, 554, 628, 631, 591, 610, 460, 464], dtype=int64),
 array([0.  , 0.07, 0.01, 0.03, 0.  , 0.  , 0.02, 0.  , 0.16, 0.07]))

In [48]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, rf_predictions))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, rf_predictions))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, rf_predictions)))  

Mean Absolute Error: 58.5
Mean Squared Error: 5273.9
Root Mean Squared Error: 72.62162212454359


In [51]:
feature_list=X_train.columns

In [52]:
# Get numerical feature importances
importances = list(model.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: Paved_Highways       Importance: 0.29
Variable: Average_income       Importance: 0.28
Variable: Population_Driver_licence(%) Importance: 0.28
Variable: Petrol_tax           Importance: 0.16


In [67]:
type(feature_list)
feature_list

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)'],
      dtype='object')

In [77]:
# New random forest with only the two most important variables
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
rf_most_important = RandomForestRegressor(n_estimators= 1000, random_state=42)
# Extract the two most important features
important_indices = [feature_list[2], feature_list[1]]
train_important = X_train.loc[:, ['Paved_Highways','Average_income','Population_Driver_licence(%)']]
test_important = X_test.loc[:, ['Paved_Highways','Average_income','Population_Driver_licence(%)']]
# Train the random forest
rf_most_important.fit(train_important, y_train)
# Make predictions and determine the error
predictions = rf_most_important.predict(test_important)
predictions

array([605.52 , 484.654, 617.538, 583.348, 627.416, 606.741, 603.607,
       573.759, 470.905, 511.363])

In [76]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, predictions))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, predictions))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))  

Mean Absolute Error: 101.27670000000002
Mean Squared Error: 14279.571823900007
Root Mean Squared Error: 119.49716240940622


In [84]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
import os
# Pull out one tree from the forest
tree = rf_most_important.estimators_[0]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf_most_important.estimators_[0]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names =  ['Paved_Highways','Average_income','Population_Driver_licence(%)'], rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
os.chdir('C:/')
graph.write_png('tree.png')


In [85]:

os.getcwd()


'C:\\'